### ISSUE TITLE
Add/Remove?

### ISSUE THREAD

**Issue by billipo** [Aloshi/ES-config#12]
Is it an easy addition to put the all-important input_enable_hotkey, exit_emulator, load_state, and save_state in the RetroArch section of ES Config?

This is probably asking too much, but is it possible in the future to break it down even further for RetroArch and program buttons for separate emulators? I know right now that there are separate folders for NES and SNES in configs for RetroPie that override the retroarch.cfg. Any way to tap into those cfg files from inside ES Config?

Thanks!

**Comment by billipo** [comment]
Also, how would I remove ES config if I did not want it present?

**Comment by Aloshi** [comment]
It's pretty simple to add the input_enable_hotkey, exit_emulator, load_state, and save_state buttons.  I just keep working on things that aren't ES-config. :smile:

As for "breaking down" RetroArch - I think the best way to do that would be to copy the script for RetroArch and just change the name and "config out" path.  It would be more tightly integrated with RetroPie than ES-config.  I would at least like to add a `<include file="retroarch_config.xml" elements="declarationScript|initScript|perPlayerScript|perInputScript|input">` that would automatically copy most of the RetroArch script to keep duplication down.

**Comment by billipo** [comment]
Thanks for the feedback and applause for all the work you have put into this project.

**Comment by Aloshi** [comment]
Oh, and to remove ES-config you can just delete the folder (I think it's in `~/RetroPie/supplementary/es-config`?).  If you're using RetroPie, also delete `/usr/bin/es-config`, the launch script.
