### ISSUE TITLE
Script error when trying to save config

### ISSUE THREAD

**Issue by Zarniwoop79** [Aloshi/ES-config#16]
Hi!

I haven't managed to get either NES or SNES controllers working. When I configure them I have to configure all buttons even for a NES controller (putting the same value for more than one button), but even when I use a SNES controller, when I choose "Save" on the last page (I assume) I get "Script error", and the settings are never saved.

Could you explain how and where I can configure manually or if there is a way to fix it?

This is on Raspberry Pi running the RetroPie project. I found some instructions on doing "git pull", but it seems that doesn't work for me (maybe only for people who've done manual installation)

Regards,

David

PS. Great work setting this up though :-)

**Comment by Zarniwoop79** [comment]
I should add that the NES and SNES controllers are of course the USB-versions of the controllers. I.e. looks exactly as they did "back then", but with USB-cable.

**Comment by Aloshi** [comment]
Try only configuring for RetroArch.  Does the error go away?

**Comment by Zarniwoop79** [comment]
Thank you! That worked :-). But the configuration doesn't seem to apply to the NES emulator. Do I have to configure each emulator separately, and if so how? (or is that out of scope for this forum?)

**Comment by Zarniwoop79** [comment]
Sorry. Got it working. I realised that the first configuration is for the menu system and the second is for the games. Now it works in both SNES and NES. The button naming is a bit confusing but I'll figure it out (B and A in the list vs on the example).
