### ISSUE TITLE
Can't Launch

### ISSUE THREAD

**Issue by CTurt** [Aloshi/ES-config#17]
I'm using emulation station, and retropie pre compiled images running off my USB stick connected to my model B raspberry pi.

Every time I launch "Input Configuration" it just displays terminal for a split second and returns to the menu.

I've reflashed the image onto my USB three times already, and have not been able to access it.

I've got a USB switcher plugged into the second USB port, and in the switcher is a PS4 controller and a keyboard.

I was able to set up the inital controls and can browse the menu with my keyboard and PS4 controller however when I try to launch the Input Configuration it always crashes.

After it has crashed, if I press F4 I can see that it says in terminal:

/RetroPie/supplementary/ES-config ~
======================================ementary/ES-config/settings.xml

My settings.xml file looks normal, just three lines with the directories.

What am I doing wrong? Or is it meant to crash like how the default doom app crashes if you haven't put in a doom.wad?

**Comment by Aloshi** [comment]
Close ES and run `~/RetroPie/roms/esconfig/Start.sh &> ~/esconfig_log.txt` (this is the command that is executed to start ES-config, but set to redirect terminal output to the file `esconfig_log.txt` in your home directory).  You might have to change the `~/RetroPie/` part depending on how it's being run from your USB stick.  Let me know what the log says.

**Comment by CTurt** [comment]
I removed the multi USB adapter so now my pi just has a flash drive and the controller in its USB ports and did as you said. Here's what my screen currently says:

pi@raspberrypi ~/RetroPie/roms/esconfig $ ls
Start.sh
pi@raspberrypi ~/RetroPie/roms/esconfig $ Start.sh &> mylog.txt
pi@raspberrypi ~/RetroPie/roms/esconfig $ ls
mylog.txt Start.sh
pi@raspberrypi ~/RetroPie/roms/esconfig $ cat mylog.txt
bash: Start.sh: command not found

**Comment by CTurt** [comment]
Tried it again and got Start.sh line 4 segmention fault.

**Comment by CTurt** [comment]
Formatted SD card and USB; flashed ISO to USB, copied over files on primary partition to SD. Changed txt file to boot from sda2. Put on ROMs. Turn on Pi; can play games fine, but when I open Input Configuration, it just reopens the menu after the zoom effect. I really have no idea what's going on. I've tried with just a keyboard, no controller and same thing.

**Comment by Aloshi** [comment]
It sounds like it's actually crashing judging by the segfault (not just giving an error and refusing to start).  Try this to hopefully give more information:

``` bash
cd ~/RetroPie/supplementary/ES-config
gdb ./es-config
run --settings ./settings.xml
# ... wait for it to crash ...
bt
bye
```

This will start es-config attached to gdb (a debugger).  Once it crashes, "bt" will show a stack trace showing approximately where in the program the error happened.

It's also entirely possible that the crash is happening after the rendering stuff gets initialized and you'll just be left with a black screen when it crashes.  If that happens you can use the [magic sysrq key](http://en.wikipedia.org/wiki/Magic_SysRq_key#Uses) to reboot safely (or just pull the plug).

**Comment by CTurt** [comment]
I got a black screen.

**Comment by Aloshi** [comment]
Well, in the interest of just getting something that works, you can configure the emulators manually.  For RetroArch based emulators (NES, SNES, some others) you can use [this wiki entry](https://github.com/petrockblog/RetroPie-Setup/wiki/Is-there-another-way-to-set-up-the-gamepad-for-use,-e.g.,-withing-the-snes-emulator%3F).  Others don't have their own config utility, so you'll have to write the config file by hand.  [This is what a dgenrc file looks like](https://github.com/trevornunes/DGEN/blob/master/src/sample.dgenrc) (some more info on the format [here](http://manpages.ubuntu.com/manpages/hardy/en/man5/dgenrc.5.html) too).  The GnGeo format is godawful so hopefully you don't have to use it...but if you do, [here are some examples](https://github.com/ymartel06/GnGeo-Pi/wiki/Controllers).  The settings.xml file should tell you where the config files should go.

**Comment by CTurt** [comment]
Yay, it's not the easiest way to configure, but I did it! I had to change the directory, it wasn't correct for some reason.
